.\" -*- coding: us-ascii -*-
.TH xdbedizzy __appmansuffix__ __xorgversion__
.SH NAME
xdbedizzy \- demo of DBE creating a double buffered spinning scene
.SH SYNOPSIS
.ad l
\fBxdbedizzy\fR \kx
.if (\nxu > (\n(.lu / 2)) .nr x (\n(.lu / 5)
'in \n(.iu+\nxu
[\fB\-display \fBhost:dpy\fR\fR] [\fB\-delta \fBdlt\fR\fR] [\fB\-class \fBvisclass\fR\fR] [\fB\-depth \fBvisdepth\fR\fR] [\fB\-visid \fBvisualid\fR\fR] [\fB\-list\fR] [\fB\-nodb\fR] [\fB\-help\fR] [\fB\-speed \fBnumber\fR\fR] [\fB\-sync\fR] [\fB\-spokes \fBn\fR\fR] [\fB\-verbose\fR]
'in \n(.iu-\nxu
.ad b
.SH DESCRIPTION
xdbedizzy is a demo of DBE creating a double
buffered spinning scene.
.SH OPTIONS
.TP 
\fB\-display \fIhost:dpy\fB\fR 
This option specifies the X server to contact.
.TP 
\fB\-class \fIvisclass\fB\fR 
Name of visual to choose. Valid values are
TrueColor, DirectColor, PseudoColor, StaticColor, Grayscale, StaticGray
.TP 
\fB\-depth \fIdepth\fB\fR 
Depth of visual to use.
.TP 
\fB\-visid \fIvisualid\fB\fR 
Visual ID to use (ignore \fB\-class\fR,
\fB\-depth\fR).
.TP 
\fB\-list\fR 
List double buffer capable visuals.
.TP 
\fB\-nodb\fR 
Single buffer (ignore \fB\-class\fR,
\fB\-depth\fR, \fB\-visid\fR).
.TP 
\fB\-help\fR 
Prints usage and exists.
.TP 
\fB\-speed \fIvalue\fB\fR 
Defines the time to delay between frames as delay=2sec/speed.
Default value is 20.
.TP 
\fB\-sync\fR 
Use synchronous X connection.
.TP 
\fB\-spokes \fIvalue\fB\fR 
Specify number of spokes to draw. The default value is 12.
.TP 
\fB\-verbose\fR 
Print verbose output.
.SH "SEE ALSO"
\fBDBE\fR(__libmansuffix__), \fBXdbeSwapBuffers\fR(__libmansuffix__), \fBXdbeGetVisualInfo\fR(__libmansuffix__), \fBXdbeAllocateBackBufferName\fR(__libmansuffix__), \fBX\fR(__miscmansuffix__), \fBXserver\fR(__appmansuffix__)
.SH ENVIRONMENT
.TP 
\fBDISPLAY\fR 
\fBDISPLAY\fR must be set to get the default host and display to use.
.SH AUTHOR

Mark Kilgard
.PP
Allen Leinwand
.PP
Roland Mainz

